author:
  email: anon@anon.com
  name: Anonymous
baseurl: /lelo_ex_sky130a
description: The answer is 42
domain: analogicus.github.io
exclude:
- Gemfile
- Gemfile.lock
- node_modules
kramdown:
  mathjax: true
markdown: kramdown
minima:
  skin: classic
plugins:
- jekyll-feed
- jemoji
- jekyll-seo-tag
- jekyll-remote-theme
- jekyll-paginate
remote_theme: wulffern/minima
show_excerpts: false
title: LELO_EX_SKY130A
url: https://analogicus.github.io
