name: DRC

on:
  push:
    branches: ["main"]
    paths:
      - 'design/**.mag'
      - 'info.yaml'
      - 'config.yaml'
  workflow_dispatch:

concurrency:
  group: "drc"
  cancel-in-progress: true

jobs:
  drc:
    uses: karlside/jnw-actions/.github/workflows/drc.yaml@main
